imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# Enables Mink and configure it
behat_mink:
    base_url:  http://knpipsum-for-symfony.dev/app_test.php/

# Enables Behat
behat: ~
