_mupowatch:
  resource: "@InoriMupoWatchBundle/Resources/config/routing.yml"

_admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type:     sonata_admin
    prefix:   /admin
    
    
#_imagine:
#    resource: .
#    type:     imagine
#    